### ISSUE TITLE
Build throws Cannot set property nodeModulesPath of #<Class> which has only a getter for >=0.1.10

### ISSUE THREAD

**Issue by jelhan** [FortAwesome/ember-fontawesome#101]
Upgrading `@fortawesome/ember-fontawesome` from `0.1.9` to `0.1.10` or higher breaks build (and all other Ember CLI commands). It throws: `Cannot set property nodeModulesPath of #<Class> which has only a getter`

It seems to be related to https://github.com/FortAwesome/ember-fontawesome/commit/9eaa462a020ef98c4ebdd65c0874087f3c0745d9.

```
$ ember -v
ember-cli: 2.18.2
node: 8.15.1
os: linux x64
```

Since it may be related to `broccoli-rollup`:

```
$ yarn list --pattern broccoli-rollup
yarn list v1.15.2
├─ broccoli-rollup@2.1.1
└─ ember-data@2.16.3
   └─ broccoli-rollup@1.3.0
Done in 1.10s.
```

Error report by Ember CLI:

```
 VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.33.0
  - node: 8.15.1
  - openssl: 1.0.2r
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.23.2
  - v8: 6.2.414.75
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot set property nodeModulesPath of #<Class> which has only a getter
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot set property nodeModulesPath of #<Class> which has only a getter
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot set property nodeModulesPath of #<Class> which has only a getter
    at assignProperties (/home/main/Code/fey/pruefung-client/node_modules/core-object/lib/assign-properties.js:68:19)
    at Function.extend (/home/main/Code/fey/pruefung-client/node_modules/core-object/core-object.js:43:7)
    at Function.Addon.lookup (/home/main/Code/fey/pruefung-client/node_modules/ember-cli/lib/models/addon.js:1765:27)
    at graph.each (/home/main/Code/fey/pruefung-client/node_modules/ember-cli/lib/models/addons-factory.js:54:38)
    at Vertices.each (/home/main/Code/fey/pruefung-client/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/home/main/Code/fey/pruefung-client/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/home/main/Code/fey/pruefung-client/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/home/main/Code/fey/pruefung-client/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
    at Project.initializeAddons (/home/main/Code/fey/pruefung-client/node_modules/ember-cli/lib/models/project.js:442:38)
    at Project.eachAddonCommand (/home/main/Code/fey/pruefung-client/node_modules/ember-cli/lib/models/project.js:504:12)
```

**Comment by lougreenwood** [comment]
I'm also seeing this issue, specifically when using `corber` (http://corber.io) to build my Cordova apps.

Thank you @jelhan for tracking this down! :)

**Comment by lougreenwood** [comment]
I'm also seeing this issue, specifically when using `corber` (http://corber.io) to build my Cordova apps.

Thank you @jelhan for tracking this down! :)

**Comment by lougreenwood** [comment]
I'm also seeing this issue, specifically when using `corber` (http://corber.io) to build my Cordova apps.

Thank you @jelhan for tracking this down! :)

**Comment by robmadole** [comment]
@jelhan @lougreenwood can you provide a reproducible test case? A GitHub repo or similar?

**Comment by jelhan** [comment]
@robmadole Played a little bit around and found a simple reproduction:

```sh
git clone --single-branch --branch v2.18.2 https://github.com/ember-cli/ember-new-output.git ember-fontawesome-bug
cd ember-fontawesome-bug
yarn install
ember install @fortawesome/ember-fontawesome
```

The error `Cannot set property nodeModulesPath of #<Class> which has only a getter` is already thrown by trying to install `@fortawesome/ember-fontawesome` with ember / ember-cli 2.18.2.

**Comment by jrjohnson** [comment]
A bit of investigation tonight and I think that `ember-cli` in some versions defines a `nodeModulesPath` which conflicts with our definition [here](https://github.com/FortAwesome/ember-fontawesome/blob/master/index.js#L20). I would guess that just changing that variable name will clear up this bug. @jelhan would you like to try that and see if it works? A PR with the change would be welcome.
