### ISSUE TITLE
Class constructor Plugin cannot be invoked without 'new'

### ISSUE THREAD

**Issue by btecu** [FortAwesome/ember-fontawesome#148]
Using `ember-cli` 3.18 and getting:

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Class constructor Plugin cannot be invoked without 'new'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Class constructor Plugin cannot be invoked without 'new'
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Class constructor Plugin cannot be invoked without 'new'
    at new BroccoliMergeTrees (C:\Code\myaddon\node_modules\broccoli-merge-trees\index.js:16:10)
    at Class.treeForVendor (C:\Code\myaddon\node_modules\@fortawesome\ember-fontawesome\index.js:84:12)
    at Class._treeFor (C:\Code\myapp\node_modules\ember-cli\lib\models\addon.js:696:33)
    at Class.treeFor (C:\Code\myapp\node_modules\ember-cli\lib\models\addon.js:656:21)
    at C:\Code\myapp\node_modules\ember-cli\lib\models\addon.js:525:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (C:\Code\myapp\node_modules\ember-cli\lib\models\addon.js:522:24)
    at Class.treeFor (C:\Code\myapp\node_modules\ember-cli\lib\models\addon.js:655:22)
    at C:\Code\myapp\node_modules\ember-cli\lib\broccoli\ember-app.js:711:26
    at Array.reduce (<anonymous>)
```

It might be related to some `babel` update, because it used to work.
Any idea what might be wrong?

**Comment by btecu** [comment]
Issue went way after cleaning up `node_modules` and re-installing. It might have been some bad transient dependency.

**Comment by jrjohnson** [comment]
Great news. Tha ks for closing!
