### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by gossi** [FortAwesome/ember-fontawesome#18]
I created an addon (`ember addon <my-addon>`), turned that addon into an engine (`ember install ember-engines`). Installed ember-fa (`ember install @fortawesome/ember-fontawesome`), installed the pro icon packs with yarn (`yarn add @fortawesome/fontawesome-pro-*@5.1.0-3`). Which put `@fortawesome/ember-fontawesome` in `devDependencies` and the icon packs in `dependencies`. I did reexported the `{{fa-icon}}`, like so:

```
// addon/components/fa-icon.js
export { default } from '@fortawesome/ember-fontawesome/addon/components/fa-icon';
```

and used it in the application template. I did ran the dummy test app: `ember s` which resulted in this error:

```
Could not find module `@fortawesome/ember-fontawesome/addon/components/fa-icon`
```

So I moved `@fortawesome/ember-fontawesome` from `devDependencies` to `dependencies` and run `ember s` again, which gives me this one:

```
$ ember s
Cannot read property 'options' of undefined


Stack Trace and Error Report: /var/folders/tv/67gb0k1s7yz4f0cgn8kvqbj00000gn/T/error.dump.912a76e8916c766d1934d39886abfbab.log
```

The log has the following trace:

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'options' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'options' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'options' of undefined
    at Class.buildConfig (/path/to/my-engine/node_modules/@fortawesome/ember-fontawesome/index.js:84:40)
    at Class.included (/path/to/my-engine/node_modules/@fortawesome/ember-fontawesome/index.js:126:35)
    at Class.superWrapper [as included] (/path/to/my-engine/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/path/to/my-engine/node_modules/ember-cli/lib/models/addon.js:381:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/path/to/my-engine/node_modules/ember-cli/lib/models/addon.js:378:24)
    at Class.included (/path/to/my-engine/node_modules/ember-cli/lib/models/addon.js:648:10)
    at Class.superWrapper [as included] (/path/to/my-engine/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.included (/path/to/my-engine/node_modules/ember-engines/lib/engine-addon.js:605:28)
    at project.addons.project.addons.filter.addon (/path/to/my-engine/node_modules/ember-cli/lib/broccoli/ember-app.js:542:17)
```

I traced it down to this line: https://github.com/FortAwesome/ember-fontawesome/blob/ca803d840a5226778fd2dccdd666e828a4a0509b/index.js#L84 

There is no `this.app`, this is `undefined` when the dummy app of an addon is ran. I "fixed" this locally for me with:

```
if (!this.app) { this.app = {}; }
if (!this.app.options) { this.app.options = {}; }
```

so badly 😁 I'm pretty sure, there is a stable API to that ;) Should be easy to fix, actually.

**Comment by robmadole** [comment]
Cool, we'll get it on the list, @gossi
