### ISSUE TITLE
Error: "Insufficient rollup version" when updating to latest version

### ISSUE THREAD

**Issue by gzurbach** [FortAwesome/ember-fontawesome#231]
**Describe the bug**

We're currently on 0.4.1 trying to update to 1.0.0. When building the app, we're getting the following error from broccoli:

```
Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.77.2.
nodeName: fontawesome-svg-core
```

We haven't had a chance to investigate why this is happening yet. There might be an easy solution... we thought we'd report to know if anyone else has run into this issue and how they solved it.

**Expected behavior**

Updating to latest version should not break the build.

**Additional context**

- Ember version: 4.6
- Full error stack:

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.77.2.
    at validateVersion (/home/runner/work/webapp/webapp/node_modules/@fortawesome/ember-fontawesome/node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:953:11)
    at Object.buildStart (/home/runner/work/webapp/webapp/node_modules/@fortawesome/ember-fontawesome/node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:[119](https://github.com/repo/webapp/actions/runs/5108642836/jobs/9226460309#step:5:120)7:7)
    at /home/runner/work/webapp/webapp/node_modules/rollup/dist/shared/rollup.js:22826:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async /home/runner/work/webapp/webapp/node_modules/rollup/dist/shared/rollup.js:23679:13
    at async catchUnfinishedHookActions (/home/runner/work/webapp/webapp/node_modules/rollup/dist/shared/rollup.js:23162:20)
    at async rollupInternal (/home/runner/work/webapp/webapp/node_modules/rollup/dist/shared/rollup.js:23677:5)
    at async RollupHelper.rollup (/home/runner/work/webapp/webapp/node_modules/broccoli-rollup/dist/rollup-helper.js:68:27)
    at async RollupHelper.build (/home/runner/work/webapp/webapp/node_modules/broccoli-rollup/dist/rollup-helper.js:31:32)
  - code: [undefined]
  - codeFrame: Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.77.2.
  - errorMessage: Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.77.2.
        at fontawesome-svg-core
```

**Comment by gzurbach** [comment]
For anyone wondering, we were able to solve this by "resetting" our dependency tree:

```sh
rm -rf node_modules
rm package-lock.json
npm i
```

Closing this issue.
