### ISSUE TITLE
0.1.8 doesn't work in an addon

### ISSUE THREAD

**Issue by BryanCrotaz** [FortAwesome/ember-fontawesome#82]
in Line 21 of` index.js`, `this.fontawesomeConfig` is null. This causes the build to fail.

This happens when ember-fontawesome is used within an addon and that is wrapped in another addon:

`app -> addon1 -> addon2 -> ember-fontawesome`

Building `addon2` succeeds.
Building `addon1` fails.

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'icons' of null
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'icons' of null
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'icons' of null
    at Class.treeForVendor (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/@fortawesome/ember-fontawesome/index.js:21:39)
    at Class._treeFor (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:617:33)
    at Class.treeFor (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:577:21)
    at addons.reduce (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:450:26)
    at Array.reduce (native)
    at Class.eachAddonInvoke (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:447:24)
    at Class.treeFor (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:576:22)
    at addons.reduce (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:450:26)
    at Array.reduce (native)
    at Class.eachAddonInvoke (/root/src/bitbucket.org/silvercurve/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/addon.js:447:24)
```

**Comment by jrjohnson** [comment]
@BryanCrotaz I'm using this in exactly this way, can you provide access to a reproduction where this fails so I can check it out?

**Comment by jrjohnson** [comment]
Closing until a reproduction can be provided.
