### ISSUE TITLE
Error building with 0.1.12

### ISSUE THREAD

**Issue by robclancy** [FortAwesome/ember-fontawesome#95]
```
=================================================================================

ENV Summary:

  TIME: Wed Feb 20 2019 19:05:34 GMT-0300 (Chile Summer Time)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /home/robbo/.yarn/bin/ember
  - s
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /usr/bin/zsh
  PATH: --
  PLATFORM: linux x64
  FREEMEM: 1870454784
  TOTALMEM: 16686784512
  UPTIME: 28430
  LOADAVG: 3.205078125,2.79296875,3.1376953125
  CPUS:
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3459
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3429
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3433
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3411
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3512
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3440
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3416
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3413
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 34.0
  - http_parser: 2.9.0
  - icu: 63.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.36.0
  - node: 10.15.1
  - openssl: 1.1.1a
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.26.0
  - v8: 6.8.275.32-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: ERR_INVALID_ARG_TYPE
  - codeFrame: [undefined]
  - errorMessage: The "path" argument must be of type string. Received type undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: The "path" argument must be of type string. Received type undefined
  - name: TypeError [ERR_INVALID_ARG_TYPE]
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1152:7)
    at addons.map.addon (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:18:27)
    at Array.map (<anonymous>)
    at processAddons (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:17:27)
    at getIcons (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:28:20)
    at discoverConfiguredIcons (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:11:17)
    at Class.readConfig (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/index.js:119:29)
    at Class.included (/home/robbo/projects/postedin/platform/app/node_modules/@fortawesome/ember-fontawesome/index.js:182:10)
    at Class.superWrapper [as included] (/home/robbo/projects/postedin/platform/app/node_modules/core-object/lib/assign-properties.js:34:20)

=================================================================================
```

**Comment by jrjohnson** [comment]
Thanks for reporting @robclancy. It looks like there may be a case where something isn't set the way I thought it would be. Can you share an app with this error to that I can debug?

**Comment by robclancy** [comment]
There is nothing special in our app. Just including the packages in package.json. No extra config. I'm leaving the office now but can check tomorrow incase one of our dependencies is clashing somehow.

**Comment by jrjohnson** [comment]
OK, let me know. It's running in my app and addon as well as a sample yarn workspace I built to test deeply nested situations.

**Comment by robclancy** [comment]
Okay so we have an addon that is to do some custom things when building with `index.html` and styles. It isn't an addon used at runtime so has no `app` or `addon` folder. Therefore `addon.root` is undefined.

**Comment by robclancy** [comment]
I don't know if there is a specific reason for the `root` to be undefined, I added `app` and `addon` folders but same error.

I was able to fix it simply with...
```js
function processAddons(addons) {
  const allIcons = addons.filter(a => a.root).map(addon => {
    const iconPath = path.join(addon.root, 'config', 'icons.js');
    return getIcons(addon, iconPath);
  });

  return allIcons.reduce((accumulator, obj) => {
    return combineIconSets(accumulator, obj);
  }, {});
}
```
But I don't know if that is the "correct" way to check for this sort of issue.

**Comment by jrjohnson** [comment]
This looks good to me @robclancy. Care to make it a PR?

**Comment by robclancy** [comment]
https://github.com/FortAwesome/ember-fontawesome/pull/96
